### ISSUE TITLE
simuvex.engines.vex.engine error while analyzing statement

### ISSUE THREAD

**Issue by deepgray** [angr/angr-doc#134]
OS Ubuntu 16.04 LTS amd64 dist-upgraded to current.
while trying a verifiation run on the install, Angr appears to get most of the flags in the cmu_binary_bomb example, but blows a lot of error messages regarding simuvex analyzing a statement (10)...

python version is 2.7.12

installed via pip install angr

attached is the output from the run showign the error message.

[output.txt](https://github.com/angr/angr-doc/files/966342/output.txt)

**Comment by zardus** [comment]
The exceptions that are printed are caused by the `LAZY_SOLVES` option, which takes the hit of exploration of "zombie" states in exchange for less frequent SMT solving. Because of the confusion caused by these exceptions, we've actually disabled the `LAZY_SOLVES` option by default in the git version (which will hopefully be released soon).

Regarding the cause of the actual failure, my guess would be that you ran out of RAM. How much RAM do you have? Program analysis is obnoxiously expensive.

**Comment by deepgray** [comment]
had it low..in a VM so i'll increase it...how about cores? 2 sufficient?

**Comment by deepgray** [comment]
increased the memory to 16 GB and same result

**Comment by deepgray** [comment]
Increasing to 16 GB of memory, similar results but got further, then python segfaults...

[output.txt](https://github.com/angr/angr-doc/files/968213/output.txt)

**Comment by deepgray** [comment]
i see where LAZY_SOLVES is defined in s_options.py...is there a settings file somewhere that overrides this since there is a s_options.pyc?

**Comment by zardus** [comment]
You can pass `remove_options={LAZY_SOLVES}` when you create a state to remove it, or update to the git version for now, where it's disabled by default.

Can you check the output of `dmesg` to see where python segfaults?

**Comment by rhelmot** [comment]
This should be resolved. Please let me know if it's not.
