### ISSUE TITLE
Example defcamp_r200 is currently broken

### ISSUE THREAD

**Issue by Kira-cxy** [angr/angr-doc#170]
Not sure what we did to break it, python raise Index out of range Error after 99999 rounds.

**Comment by rhelmot** [comment]
Having spent a while looking into this, merging is very badly broken.

@ltfish @zardus one of you needs to pick this up. Here's a more minimal testcase:

```python
import angr
import logging

def main():
    p = angr.Project("r200", auto_load_libs=False)
    sm = p.factory.simulation_manager()

    # avoid the antidebug traps, go to the merge point
    sm.explore(find=0x4007FD, avoid=(0x40085D, 0x400882), num_find=11)
    print sm

    var_addr = sm.one_found.solver.eval(sm.one_found.regs.rbp - 0x4c)
    for s in sm.found:
        print s, s.mem[var_addr].dword.resolved

    print 'merging...'
    sm.merge(stash='found')

    s = sm.one_found
    culprit = s.mem[var_addr].dword.resolved
    print s, culprit.__repr__(max_depth=3)
    for i in xrange(1, 0xb):
        print i, s.solver.satisfiable(extra_constraints=(culprit == i,))

if __name__ == '__main__':
    logging.getLogger('angr.state_plugins.callstack').setLevel('ERROR')
    #logging.getLogger('angr.manager').setLevel('DEBUG')
    #logging.getLogger('angr.exploration_techniques.manual_mergepoint').setLevel('DEBUG')
    main()
```

I get this for output:

```
<SimulationManager with 11 found, 2 avoid>
<SimState @ 0x4007fd> <BV32 0xa>
<SimState @ 0x4007fd> <BV32 0x9>
<SimState @ 0x4007fd> <BV32 0x8>
<SimState @ 0x4007fd> <BV32 0x7>
<SimState @ 0x4007fd> <BV32 0x6>
<SimState @ 0x4007fd> <BV32 0x5>
<SimState @ 0x4007fd> <BV32 0x4>
<SimState @ 0x4007fd> <BV32 0x3>
<SimState @ 0x4007fd> <BV32 0x2>
<SimState @ 0x4007fd> <BV32 0x1>
<SimState @ 0x4007fd> <BV32 0x0>
merging...
<SimState @ 0x4007fd> <BV32 Reverse((if And(<...>, <...>, <...>) then (if <...> then <...> else <...>) else (if <...> then <...> else <...>)))>
1 False
2 False
3 False
4 False
5 False
6 False
7 False
8 False
9 True
10 True
```

i.e. even though a given variable can be a certain value before merging, it can't be that value after merging.

**Comment by ltfish** [comment]
@rhelmot It's actually not a bug. We introduced a new state option, `EFFICIENT_STATE_MERGING`, during the major refactor. This option allows us to store a strong reference to `SimState`s inside `SimStateHistory` instances in order to enable optimal merging, which requires the common ancestor state to be specified. Enabling `EFFICIENT_STATE_MERGING` will make your minimal test case to work.

I opened [a PR for angr](https://github.com/angr/angr/pull/802) to allow a semi-optimal state merging without that state option. It should also address this issue. I don't have enough battery power to run the tests right now. Please test this example with that PR. Thank you!

**Comment by rhelmot** [comment]
You've got a lot of nerve saying "actually it's not a bug" in the face of merging just straight up giving us incorrect results with default settings :P
