### ISSUE TITLE
SimProcedureError: Tried to run simproc continuation with empty stack

### ISSUE THREAD

**Issue by bynop** [angr/angr-doc#27]
there is something wrong with "Defcamp CTF Qualification 2015 - Reversing 200" sample code.

after update to latest version, it through an error like this

ERROR   | 2016-01-13 21:48:23,492 | angr.analyses.cfg | SimError: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg.py", line 776, in _get_simrun
    sim_run = self.project.factory.sim_run(current_entry.state, jumpkind=jumpkind)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 114, in sim_run
    r = sim_proc_class(state, addr=addr, sim_kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/s_procedure.py", line 227, in __new__
    raise SimProcedureError("Tried to run simproc continuation with empty stack")
SimProcedureError: Tried to run simproc continuation with empty stack

**Comment by ltfish** [comment]
Thanks for telling us. This is a problem in my Veritesting implementation where it tries to start CFG recovery from the middle of the program (instead of the beginning) and some context information is missing. I haven't figured a good way to handle that (other than just mute this error). However, it shouldn't affect Veritesting at all. So don't worry about it.

**Comment by bynop** [comment]
thanks for your explaintion~~
