### ISSUE TITLE
Resolve automatically

### ISSUE THREAD

**Issue by josslalou** [angr/angr-doc#358]
we still have one problem which, I think is hard to manage: resolving challenges automatically, i.e. without entering the addresses beforehand: what can be done for the hooks functions and for the find address (in the function from angr: "explore") i think it's pretty hard but i hope you can help
joss Lalou
thanks once again 🥇

**Comment by rhelmot** [comment]
For the hook addresses, there is no easy solution. In the future, we would like to have FLIRT signatures on-hand in order to be able to identify linked-in implementations of scanf and friends, but for now there is no way to do this automatically.

For the find address, you can actually avoid specifying or recovering any address by specifying your find condition as a lambda which evaluates the given state's stdout and seeing what message it holds.

**Comment by josslalou** [comment]
Is there a function in which we list the function names used with their specific addresses?

**Comment by rhelmot** [comment]
No, this information is discarded by the compiler usually.

**Comment by josslalou** [comment]
![image](https://user-images.githubusercontent.com/57400419/121417816-f7749700-c972-11eb-8480-073b51cb6b49.png)
see that

**Comment by rhelmot** [comment]
This is a case where the information is not discarded by the compiler because the implementation is dynamically linked. Your examples do not do this.

**Comment by josslalou** [comment]
I think I understood , but I think I understood, another problem (if I ever waste your time I'm sorry I have an assignment on it which is coming soon) in the binary file below I can not find any way to solve with angr, even after adding hook functions, if you can help me thanks! 
thank you for all you help me already!
joss lalou
[level1_d.zip](https://github.com/angr/angr-doc/files/6626484/level1_d.zip)

**Comment by rhelmot** [comment]
We can't do your homework for you.

**Comment by josslalou** [comment]
i have do the code already but this return an error ...

**Comment by rhelmot** [comment]
What is your error?

**Comment by josslalou** [comment]
![image](https://user-images.githubusercontent.com/57400419/121420069-563b1000-c975-11eb-8524-b6910133efbe.png)

**Comment by rhelmot** [comment]
this means that the simulation manager's active stash is empty. This can be debugged by printing out the simulation manager object to tell what its contents are. The states generally don't go nowhere, so the question is, where have they gone?

**Comment by josslalou** [comment]
![Uploading image.png…]()

**Comment by rhelmot** [comment]
so uh, there are a few problems.

1) you didn't actually follow my instructions. I told you to print out your simulation manager object in order to debug why the active stash is empty, and you seem to have written an entirely new example
2) you have misspelled "addr" as "add" in the state constructor. This is why the warning about the unused keyword argument appears in your output, and it is definitely making it so that you are not simulating what you want to be.

**Comment by josslalou** [comment]
![image](https://user-images.githubusercontent.com/57400419/121421983-681db280-c977-11eb-9897-ebebcebd7458.png)

**Comment by rhelmot** [comment]
You seem to be using me as a personal debugger, which I do not appreciate. I am going to stop helping you since you do not seem to be invested in figuring out how angr works and you are not able to follow my instructions.
