### ISSUE TITLE
Trouble Getting Expected Angr Results

### ISSUE THREAD

**Issue by Owlz** [angr/angr-doc#6]
Hey,

So this is probably a user error, but I created a binary to test my understanding of angr. Basically, all it does is ask for input, then check that against a static "P@ssword", and branch accordingly. I've been able to get angr to find the path just fine, but I can never get it to tell me that the only way to get through to that path is to use the "P@ssword".

Here's my simple script:
import angr
import simuvex
b = angr.Project("a.out")
e = b.surveyors.Explorer(find=(0x400695))
e.run()
s = e.found[0].state
s.se.any_str(s.memory.load(s.regs.rbp-0x110,16))

The C code is this (gcc test.c):
#include <stdio.h>
int main() {
  char buf[256];
  printf("Enter password: ");
  gets(buf);
  if (strcmp(buf,"P@ssword")) {
    printf("%s is correct\n",buf);
  }
  else {
     printf("%s is incorrect\n",buf);
  }
  return 0;
}

**Comment by rhelmot** [comment]
Well problem number one is that you have the condition on the password backwards-- strcmp returns zero when the two strings are equal.

Fixing that and then adjusting the addresses and offsets for the results of my gcc (for me it's `rbp - 0x100`), angr does find it! I'm actually a little surprised by that, since there's no SimProcedure for `gets`, so it had to step down into libc and perform the real syscalls in order to do the read.

**Comment by Owlz** [comment]
Doh! Yeah, been staring at the screen too long. In any case, awesome tool! Keep up the good work!
