### ISSUE TITLE
Does Angr depends on some particular features of architectures?

### ISSUE THREAD

**Issue by leithon** [angr/angr-doc#96]
I wrote a simple ReverseMe progam just like the example of Baby-re.
Beside, I wrote a similar script just like that of the Baby-re.

However, the script hangs in my platform (ubuntu-16.04), whereas it works well in another platform of Mac.

So, does Angr depend on some particular features of architectures?

**Comment by zardus** [comment]
It *shouldn't*... Could you Ctrl-C it on ubuntu and see where it hung?

**Comment by leithon** [comment]
In the Mac, the result is 
<SAO <BV64 0x7fffffffffeffe0>>
<SAO <BV64 0x7fffffffffeffe0>>
<SAO <BV64 0x7fffffffffeffe0>>
<SAO <BV64 0x7fffffffffeffe0>>
<SAO <BV64 0x7fffffffffeffe0>>

**Comment by rhelmot** [comment]
This is now over a year old, so I'm going to close it since the relevant parts of the code have almost certainly changed by now. My best guess is that it's some issue in z3 itself, or possibly the platform difference contributing to how implicit concretizations played out, making the solution possible or not possible.

If this is still an problem please open a new issue with a testcase.
